# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog', '0002_auto_20160314_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publish date')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_blog.Topic')),
            ],
        ),
    ]
