# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='topic',
            name='docfile',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
