# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog', '0004_auto_20160315_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='docfile',
            field=models.FileField(null=True, upload_to='messages/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='docfile',
            field=models.FileField(null=True, upload_to='topics/'),
        ),
    ]
