# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 12:22
from __future__ import unicode_literals

from django.db import models, migrations


def load_data(apps, schema_editor):
    Category = apps.get_model('simple_blog', 'Category')

    locations = Category(id=0, name='Locations', protected=False)
    locations.save()

    hr = Category(id=1, name='HR', protected=True)
    hr.save()

    Subcategory = apps.get_model('simple_blog', 'Subcategory')

    odessa = Subcategory(id=0, category_id=0, name='Odessa')
    odessa.save()

    lublin = Subcategory(id=1, category_id=0, name='Lublin')
    lublin.save()

    secret = Subcategory(id=2, category_id=1, name='Secret')
    secret.save()

    Topic = apps.get_model('simple_blog', 'Topic')
    weather = Topic(id=0, subcategory_id=0, name='Weather', description='How do you like that?')
    weather.save()

    Message = apps.get_model('simple_blog', 'Message')
    answer = Message(id=0, topic_id=0, author='John', text='I like it so much!')
    answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog', '0005_auto_20160315_1127'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
